"""empty message

Revision ID: e5bc1508f9df
Revises: 
Create Date: 2021-09-01 15:02:17.690451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5bc1508f9df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divvy_table',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('stoptime', sa.DateTime(), nullable=True),
    sa.Column('bikeid', sa.Integer(), nullable=True),
    sa.Column('from_station_id', sa.Integer(), nullable=True),
    sa.Column('from_station_name', sa.String(), nullable=True),
    sa.Column('to_station_id', sa.Integer(), nullable=True),
    sa.Column('to_station_name', sa.String(), nullable=True),
    sa.Column('usertype', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('trip_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.drop_table('divvy2')
    op.drop_table('divvy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divvy',
    sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('starttime', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('stoptime', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('bikeid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_station_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('to_station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_station_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('usertype', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('trip_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('trip_id', name='divvy_pkey')
    )
    op.create_table('divvy2',
    sa.Column('trip_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('starttime', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('stoptime', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('bikeid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('from_station_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('from_station_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('to_station_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('to_station_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('usertype', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('trip_duration', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('trip_id', name='divvy2_pkey')
    )
    op.drop_table('divvy_table')
    # ### end Alembic commands ###
